### ISSUE TITLE
Can't install on IBM POWER8 machine

### ISSUE THREAD

**Issue by chenyuli1992** [eqcorrscan/EQcorrscan#317] opened 2019-07-30 22:11 UTC
Hi, when I try to install the EQcorrscan on a machine with IBM POWER8 processor, it fails to install, is the source code not compatible with the IBM processor? Thank you!

**Comment by calum-chamberlain** [comment] 2019-07-30 22:23
I honestly haven't tried on an IBM processor.  What was the error message during install and what was your install method?

**Comment by chenyuli1992** [comment] 2019-07-31 15:41
Thank you for your reply!
I first tried conda, after creating the environment, I installed obspy with pip under the eqcorrscan environment. Then I tried to install eqcorrscan with the following two command:
conda install -c conda-forge eqcorrscan
conda install -c conda-forge/label/cf201901 eqcorrscan 

Both of them showed PackagesNotFoundError:

Then I tried to use pip to install, it had the following error:
 /tmp/pip-install-f0a9yf70/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
     #include "hdf5.h"

**Comment by chenyuli1992** [comment] 2019-07-31 19:09
An update, when I try to install with the following way,
python setup.py install --user

I got the error like this:
gcc -pthread -B /apps/ibm/anaconda3/5.2.0/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/l0550903/Desktop/Data/EQcorrscan/EQcorrscan-master/include -I/home/l0550903/Desktop/Data/EQcorrscan/EQcorrscan-master/eqcorrscan/utils/lib -I/apps/ibm/anaconda3/5.2.0/lib/python3.6/site-packages/numpy/core/include -I~/.conda/include -I/apps/ibm/anaconda3/5.2.0/include/python3.6m -c eqcorrscan/utils/src/multi_corr.c -o build/temp.linux-ppc64le-3.6/eqcorrscan/utils/src/multi_corr.o -fopenmp -msse2 -ftree-vectorize
gcc: error: unrecognized command line option â-msse2â
error: command 'gcc' failed with exit status 1

Thank you very much!

**Comment by calum-chamberlain** [comment] 2019-07-31 19:51
Generally with these HPC type machine your best bet is to install as many of the dependencies as possible using the system package manager (or from source) - usually a system maintainer/manager will have control of this.  You would then install EQcorrscan from source (as you tried to above).

It looks like I have included an unsupported flag in the compile arguments.  I would recommend you clone the EQcorrscan repository:
```bash
git clone https://github.com/eqcorrscan/EQcorrscan.git
```
checkout the develop branch (optional, but the correlation functions in there are dramatically faster and more memory efficient, I just need to catch up and make a new release):
```
git checkout develop
```
Then comment out [lines 216-218](https://github.com/eqcorrscan/EQcorrscan/blob/2adc45c1270fd0ea763355f64c2fdd0e78e0ef57/setup.py#L216) of the setup.py file.  These lines add the `-msse2` and `-ftreevectorize` compile arguments.
Then try installing that, you can try using pip and installing as a user, from the EQcorrscan directory:
```
pip install . --user
```

If you find this works, you should add the IBM architecture to the list of architectures that do not support those C-flags and make a pull-request.

Apologies for the conda thing - I don't know how to build and distribute for IBM - it looks like there is a specific [`powerAI` channel](https://www.ibm.com/support/knowledgecenter/en/SS5SF7_1.6.0/navigation/pai_setupAnaconda.html) that should be used for IBM.

**Comment by calum-chamberlain** [comment] 2019-07-31 19:57
P.S. No guarantees that compile will go smoothly - I don't have access to an IBM machine, so haven't tested building there, however, happy to help in any way I can to debug any issues!

You should also run the tests once you have installed EQcorrscan to make sure that everything works as intended.  You might get some minor fails, but the main ones to worry about are the correlation tests.  See [this section](https://eqcorrscan.readthedocs.io/en/latest/intro.html#runningtests) of the docs for info on running tests.

**Comment by chenyuli1992** [comment] 2019-07-31 20:07
I tried the commands above, now it has another error:
/tmp/pip-req-build-dflc81hy/eqcorrscan/utils/src/libutils.h:32:19: fatal error: fftw3.h: No such file or directory

I installed a fftw-3.3.8 under my $HOME directory, can you tell me how to find it while compiling? Thank you so much!

**Comment by calum-chamberlain** [comment] 2019-07-31 20:16
It is probably best to install fftw into the system if possible, and it is probably worth seeking advice from the system maintainer at this point.

However, if you have no other option and have to install fftw into your home directory, you should be able to export the environment variable `STATIC_FFTW_DIR` before compiling (see [this section](https://github.com/eqcorrscan/EQcorrscan/blob/2adc45c1270fd0ea763355f64c2fdd0e78e0ef57/setup.py#L195) in the setup.py file), something like:
```bash
STATIC_FFTW_DIR="path-to-fftw-dir" pip install . --user
```

**Comment by chenyuli1992** [comment] 2019-07-31 21:09
The installation is successful now, thank you so much for your help!

**Comment by calum-chamberlain** [comment] 2019-08-01 00:05
Great! I will close this for now.  If you run into any other issues then let us know!

As an aside, so that I can avoid this in future, can you tell me what the output to the following is on your IBM machine:
```bash
python -c "from pkg_resources import get_build_platform; print(get_build_platform())"
```

**Closed by calum-chamberlain** 2019-08-01 00:05 UTC
Labels: packaging

**Comment by chenyuli1992** [comment] 2019-08-01 13:18
The output is this:
linux-ppc64le
