### ISSUE TITLE
[HELP] IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by zhong-yy** [eqcorrscan/EQcorrscan#592] opened 2024-11-22 16:00 UTC
# What do you need help with?
When I run `party.lag_calc(...)`, I encounter the following IndexError
```
...

File ~/miniconda3/envs/myenv/lib/python3.10/site-packages/EQcorrscan-0.5.dev0-py3.10-linux-x86_64.egg/eqcorrscan/utils/pre_processing.py:638, in _multi_resample.<locals>.<lambda>(args)
    631 to_resample = (
    632     (tr.data, tr.stats.delta,
    633      tr.stats.sampling_rate / float(sampling_rate),
    634      sampling_rate, _get_window(\"hann\", tr.stats.npts), tr.id)
    635     for tr in st)
    636 with ThreadPoolExecutor(max_workers) as executor:
    637     # Unpack tuple using lambda
--> 638     results = executor.map(lambda args: _resample(*args), to_resample,
    639                            chunksize=chunksize)
    640 for r, tr in zip(results, st):
    641     tr.data = r

File ~/miniconda3/envs/myenv/lib/python3.10/site-packages/EQcorrscan-0.5.dev0-py3.10-linux-x86_64.egg/eqcorrscan/utils/pre_processing.py:672, in _resample(data, delta, factor, sampling_rate, large_w, _id)
    668 Logger.debug(f\"Running resample for {_id} with {npts} data points\")
    669 Logger.debug(f\"{_id}: delta={delta}, factor={factor}, \"
    670              f\"sampling_rate out={sampling_rate}\")
    671 Logger.debug(f\"Sanity check data for {_id}, start and \"
--> 672              f\"end: {data[0]} -- {data[-1]}\")
    673 Logger.debug(f\"dtype for {_id}: {data.dtype}\")
    674 if data.dtype == np.dtype('float64'):

IndexError: index 0 is out of bounds for axis 0 with size 0"
```

Setting `ignore_length=True` can sometimes solve this problem. However, sometimes another error occurs after setting `ignore_length=True`:
```
...
File ~/miniconda3/envs/myenv/lib/python3.10/site-packages/EQcorrscan-0.5.dev0-py3.10-linux-x86_64.egg/eqcorrscan/utils/pre_processing.py:886, in _group_process(filt_order, highcut, lowcut, samp_rate, process_length, parallel, cores, stream, ignore_length, ignore_bad_data, overlap)
    881         Logger.warning(
    882             f\"Data quality insufficient between {kwargs['starttime']}\"
    883             f\" and {_endtime}\")
    884         continue
--> 886 if _endtime < stream[0].stats.endtime:
    887     Logger.warning(
    888         \"Last bit of data between {0} and {1} will go unused \"
    889         \"because it is shorter than a chunk of {2} s\".format(
    890             _endtime, stream[0].stats.endtime, process_length))
    891 return processed_streams

File ~/miniconda3/envs/myenv/lib/python3.10/site-packages/obspy/core/stream.py:645, in Stream.__getitem__(self, index)
    643     return self.__class__(traces=self.traces.__getitem__(index))
    644 else:
--> 645     return self.traces.__getitem__(index)

IndexError: list index out of range"
```
In addition, the [documentation](https://eqcorrscan.readthedocs.io/en/latest/submodules/core.match_filter.party.html#eqcorrscan.core.match_filter.party.Party.lag_calc:~:text=This%20is%20not%20recommended!) doesn't recommend setting `ignore_length=True` (why?).

The above errors are from the develop version. When I use the master version, there is another error:
```
...
File ~/miniconda3/envs/eqcorrscan0.5/lib/python3.10/site-packages/EQcorrscan-0.5.0-py3.10-linux-x86_64.egg/eqcorrscan/utils/pre_processing.py:771, in _fill_gaps(tr)
    769 tr = tr.split()
    770 gaps = tr.get_gaps()
--> 771 tr = tr.detrend().merge(fill_value=0)[0]
    772 gaps = [{'starttime': gap[4], 'endtime': gap[5]} for gap in gaps]
    773 if len(gaps):

File ~/miniconda3/envs/eqcorrscan0.5/lib/python3.10/site-packages/obspy/core/stream.py:645, in Stream.__getitem__(self, index)
    643     return self.__class__(traces=self.traces.__getitem__(index))
    644 else:
--> 645     return self.traces.__getitem__(index)

IndexError: list index out of range"
```

The error will disappear if the `pre_processed=True`. Maybe it is related to the preprocessing part inside lag_calc?

The index error also occurs for `Party.client_lag_calc()`.

# Provide an example so that we can reproduce your problem
Here is a minimum working example:  [example.zip](https://github.com/user-attachments/files/17872711/example.zip)

# What help would you like?
- I want to figure out what cause the above errors. Is it because I didn't use eqcorrscan correctly, or my input data are not formated correctly, or it is a bug of eqcorrscan?
- Any way to avoid this error?
- In addition, the lag_calc function may result in 2 different S arrivals on 2 horizontal components at the same station. How can I decide which one is better?

# What is your setup? (please complete the following information):**
 - Operating System: Ubuntu 24.04.1
 - Python version: 3.10.14
 - EQcorrscan version: 0.5.dev0

**Comment by calum-chamberlain** [comment] 2024-12-01 20:47
I'm going to close this in favour of #593 as I think you found that that was the cause of your issue.

**Comment by calum-chamberlain** [comment] 2024-12-05 23:16
On running your example it seems that this is not the same issues at #593 - your data have large gaps which is causing issues. I have proposed a fix in #595 - this seems to fix your example.

RE the two picks - this is an artefact of your templates containing multiple S-picks. The best way to deal with this is to determine which picks you want to use in your templates and remove the picks you don't want. Generally we just use the first arriving P and S picks for earthquake location and detection, so I would suggest you just retain those.

**Comment by zhong-yy** [comment] 2024-12-06 16:06
Thank you for your fix and answers. 

For the two S picks on the same station, even if I keep only one S pick at one station in my templates, I still get two S picks after running `lag_calc`. It may be because the maximum cross correlation values are reached at different locations for two horizontal channels. Now I decide to use the one with larger cross correlation value.

In addition, I found that sometimes the party object returned by `client_detect` has a pick on the horizontal channel with empty phase hint even if there is only one horizontal channel. It may be because the template labels the S pick on the other horizontal channel which is discarded during the construction of the tribe.

Here is the example [two_S_picks.zip](https://github.com/user-attachments/files/18040673/two_S_picks.zip)

**Comment by calum-chamberlain** [comment] 2024-12-08 23:26
lag-calc will return picks for all channels in the template - because you made your templates with `all_horiz=True`, you have multiple channels associated with a single pick. `lag-calc` still assumes that you want to pick S on horizontal channels and P on vertical, which will result in this additional pick. 

In this case you could:
1. Set `all_horiz=False` in `Tribe.construct`, but this does reduce the detection capability of your templates;
2. Remove channels in the templates after running `detect` but before running `lag_calc`;
3. We could implement an option to only run lag-calc on channels that have picks - I am keen to implement that as an option if you think that would be helpful?

**Comment by calum-chamberlain** [comment] 2024-12-10 19:50
Sounds good - in that case, to guarantee that your picks are labelled correctly you may want to copy the S picks to the other unpicked channel. At the moment lag-calc is complaining that there are unlabelled picks and guessing that a pick on channels ??1, ??2, ??E, ??N should be S picks. If you have data that do not use those channel naming conventions your additional S picks may be mislabeled or not labelled at all.

**Comment by zhong-yy** [comment] 2024-12-11 05:02
If the S picks are copied to other unpicked channels, what would happen if `all_horiz=True`?

**Comment by calum-chamberlain** [comment] 2024-12-11 20:12
In that case you should probably set `all_horiz=False`.

**Closed** 2024-12-12 20:22 UTC
