### ISSUE TITLE
OpenCv vs scipy.fftconvolve, is it really worth it? 

### ISSUE THREAD

**Issue by d-chambers** [eqcorrscan/EQcorrscan#80] opened 2017-02-26 23:55 UTC
Hello, 

First of all, great work! I am very impressed with the project so far. The documentation is excellent, the source code looks clean, and the tests seem to be coming along well.

I was getting started with EQcorrscan on python3 and had a very hard time getting OpenCV compiled and set up. After about an hour I just gave up and switched to a python 2.7 conda env so I could use conda to install OpenCV as stated in the EQcorrscan documentation.

However, I was curious if OpenCV would really be much more efficient than the tools that ship with Anaconda. I compared the OpenCV backed function from EQCorrscan with a function based around scipy.signal.fftconvolve.

On my machine (Ubuntu 16.04, 16 core i7) I found the scipy version was about twice as fast as the OpenCV version when using the default stream as a template and and randomly generated search spaces ranging from 60 seconds to 24 hours (assuming 100Hz sampling rate).  Here are the results. Normxcorr2 is the function from EQcorrscan, normxcorr1 is the scipy function, the left column is the duration of the search space. 

search space (seconds)
 | normxcorr1  | normxcorr2 | difference_%
| --- | ---| ---| ---|
60       |  0.000537 |   0.000769  |   43.140351
12394  |  0.101550  |  0.236562  |  132.951964
24728  |  0.235110  |  0.467714  |   98.934310
37062  |  0.349631  |  0.712785  |  103.867752
49397  |  0.481285  |  0.939461  |   95.198439
61731  |  0.587475  |  1.194135  |  103.265641
74065  |  0.772260  |  1.417412  |   83.540794
86400  |  0.888662  |  1.654045  |   86.127562

I, of course, didn't compile OpenCV on my machine, so perhaps it would be more efficient if I had. On the flip side, I didn't compile numpy or any of the other packages either, so I feel it might be a fair comparison. 

Anyway, I have attached the notebook for timing the two functions. I would be curious to see if anyone else gets a similar results. Regardless, I would recommend including a cross correlation function that doesn't require OpenCV as an option to make getting started, especially  on python 3, a bit easier. 

I also have some ideas that should significantly speed up the subspace detection that I will share when I get a chance. 

Keep up the good work. 

[profile_numpy_v_opencv.ipynb.zip](https://github.com/eqcorrscan/EQcorrscan/files/802425/profile_numpy_v_opencv.ipynb.zip)

**Comment by calum-chamberlain** [comment] 2017-02-27 00:28
It doesn't look like it is worth it! Thanks for that spot, I hadn't seen fftconvolve before, and will almost certainly put it in (unless you want to make a pull request?).  I ran your example on my machine with a compiled openCV and got a very similar result.

As an aside, you can install opencv3 via conda from the menpo channel:
```bash
conda config --add channels menpo
conda install opencv3
```
should work, but this does look better.

Very keen to hear speed-up ideas for subspace - I haven't had much time to play with that yet.

**Comment by d-chambers** [comment] 2017-02-27 04:39
Sure, I don't mind doing a PR, but it may not be until next weekend that I will be able to get to it.

**Comment by calum-chamberlain** [comment] 2017-02-27 04:47
I've actually spent the afternoon here playing with it - I've ended up re-writing the scipy function for multiple templates so that it doesn't have to recompute the fft of the search-window multiple times. Seems pretty fast - I think I will add it into the pull request I have going here: #78

**Comment by calum-chamberlain** [comment] 2017-02-28 02:58
Have you encountered any issues with the output of bottleneck.move_std containing zeros?

In some tests I'm running today I've noticed this, which results in an unstable cross-correlation result...

**Comment by d-chambers** [comment] 2017-02-28 03:38
What type of instability? Is it just resulting in large numbers in the CC value? I have seen this before, the behavior is undefined if the search space is zeroed because the std is in the denominator (div by zero). How does openCV handle that situation? 

Or was bottleneck incorrectly calculating a zero std? If the latter I have not seen it before.

**Comment by calum-chamberlain** [comment] 2017-02-28 03:56
It appears to be bottleneck incorrectly computing zeros, there are data the and other STD method (numpy, pandas) give real, non-zero values.

And yes, the instability occurs due to the division by zero.

Calum Chamberlain
Postdoctoral Fellow, Seismology
Victoria University of Wellington
Sent from mobile.


________________________________

**Comment by d-chambers** [comment] 2017-02-28 04:33
I have never seen that, and it is very concerning. I was under the impression that the pandas rolling std method was using bottleneck under the hood, I know xarray does. Do the other move_ methods also return 0? You are using the rolling_std from pandas correct? I was not aware numpy had a moving std function, or are you taking a different approach? 

If you have any data to upload I am happy to help you figure it out. If it is a bug in bottleneck we best report it, I know several widely used packages depend on bottleneck.

**Comment by calum-chamberlain** [comment] 2017-02-28 06:25
Hmm, it definitely does look like array does, but I'm not sure about pandas - and you are correct, I was using rolling_std, sorry I should have specified.  For numpy I just wrote a horrible little slow loop computing std on windows - I only did that to compare the result.

The data that give the issue are [here](https://www.dropbox.com/s/1plkwwj35dpb6fi/PXZ.EHZ.npy?dl=0).  Code that should reproduce the error is as follows:
```python
import bottleneck
import numpy as np

input_arr = np.load('PXZ.EHZ.npy')
std_array = bottleneck.move_std(input_arr, 121)
np.where(std_array==0)
```

**Comment by d-chambers** [comment] 2017-02-28 14:59
You are absolutely right, this looks like a bug to me. 
Interestingly, when I cast the dtype to float64 it seems to work. 

```python
import bottleneck
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

input_arr32 = np.load('PXZ.EHZ.npy').astype(np.float32)
input_arr64 = np.load('PXZ.EHZ.npy').astype(np.float64)
std_array32 = bottleneck.move_std(input_arr32, 121)
std_array64 = bottleneck.move_std(input_arr64, 121) 

print(len(np.where(std_array32==0)[0]))  # -> 22
print(len(np.where(std_array64==0)[0]))  # -> 0
```

I will go ahead and file a bug report with bottleneck, unless you wanted to do it. 

looking at the timing of the function, 

bottleneck.move_std(input_arr32, 121) takes 5.92 ms
and
bottleneck.move_std(input_arr64, 121) takes 7.05 ms

so there isn't a huge difference in performance.

**Comment by d-chambers** [comment] 2017-02-28 17:12
I submitted the bug report:

https://github.com/kwgoodman/bottleneck/issues/164

It may be that we have to use float 64 arrays rather than 32 in these operation, but it appears OpenCV handles float 32 fine. I re-ran the profile notebook and it looks like the scipy function with float 64 is between 30 and 60 % faster than openCV with float 32 for the test data set.

**Comment by calum-chamberlain** [comment] 2017-02-28 18:30
Thanks for that, stage that it should work for 64 but not 32. I wonder if it is an issue with how they cast to ctypes. Anyway, good to hear a fix. I'm at a meeting for the next couple of days, but have rewritten the internals of match filter and will create a pull request soon, which it would be great if you can test out. I'll ping you here when I make the PR.

**Comment by d-chambers** [comment] 2017-02-28 18:55
Sounds good, happy to test it.

**Comment by d-chambers** [comment] 2017-03-05 00:48
I did some additional profiling, it looks like the pure numpy rfft would be a good way to go. Pyfftw also looks promising but it would require much more thought to correctly implement than I gave it in this quick and dirty profiling. Also, I am not sure if the EQcorrscan internals load in multi-dimensional arrays like I have done here for testing. 

As soon as you merge in the OO matched filter branch I will dig in and try to figure more of it out so I can actually contribute to the codebase.

[additional_profiling.ipynb.zip](https://github.com/eqcorrscan/EQcorrscan/files/819024/additional_profiling.ipynb.zip)

**Comment by calum-chamberlain** [comment] 2017-03-05 23:36
Awesome work, the OO things shouldn't be too far away, but don't let that stop you putting things into another branch - I won't be changing the internals for OO, so we should just be able to rebase any PR once OO is merged without too many conflicts.  

However, I think you are right (email) that the pre-paring template FFT's would be ideal - I think that would be easily achieved in the Template object - As it stands the Template.detect (and Tribe.detect for a group of Templates) enforces that the continuous data and the template are processed the same (including the same length of data to extract from, because I have found that changing this changes the accuracy of the cross-correlations, probably because the FFT changes): therefore it shouldn't be hard to enforce the same FFT length in the same way.

FFTW was where I was headed with c-routines, but it would have involved requiring FFTW, which becomes hard to manage via pip... maybe we could offer both and detect if FFTW is installed and use that, otherwise use numpy? Have you thought about how to use *wisdom* in FFTW?

Maybe we can implement an EQcorrscan.big.match_filter using Dask some point soon?

**Comment by d-chambers** [comment] 2017-03-07 05:39
FFTW is on conda forge, so it shouldn't be too hard for folks to get. Obspy has recommended using Anaconda, it probably wouldn't hurt to do the same with EQcorrscan, then the dependencies become a lot easier. I agree though that it shouldn't be required. 

I haven't yet got a good grasp on wisdom in fftw. I know it is trying several methods of fft then caching the most promising for arrays of given shapes and types. It can make the first runs extremely slow though if the planning variable is set liberally. I am just using the pyfftw interface, probably wont dig into the C code.  Numpy is still outperforming fftw on single threads in my benchmarks. I need to look into using the builders interface, which apparently can be a lot faster, I just haven't had time yet.

**Comment by calum-chamberlain** [comment] 2017-07-20 22:02
So PR #94 has put a few options for correlation routines in now, and removed openCV - the compiled fftw routine is faster and more memory efficient than the SciPy routine, but requires you to install fftw, in setting everything up I found it was nearly impossible to get fftw from conda for all the operating systems, so I have redomended doing a proper install, however it is possible to get fftw from conda for most operating systems (64/32Bit complaints aside), so I might stick that in the docs, and I plan on working on a conda install for EQcorrscan in the next week or so so that people don't have to worry about compiling things themselves (setup.py takes care of compiling the EQcorrscan C library effectively at the moment).

As it stands, you would have to hack the code a bit to get to the scipy correlation routines - do you think I should make it more obvious that the option is there and add a variable to the top levels of match-filter to determine which routine to use?

I'm also thinking about including a setup config script that would test various routines to work out which is fastest for your machine (depending on memory limitations and number of CPUs) for various problem sizes that would be run during install (not sure how this would work with conda) and writes out a file that matched-filter then queries to determine which correlation routine to use.  e.g. the time-domain routine is fastest for small problems, while the frequency domain methods are faster for large problems.

I realise my C routine could just as easily be written in pure Python using PyFFTW, but, I'm still determined to get an openMP loop running to effectively parallel the correlations for SLURM (which I haven't finished yet, need to seek advice from some gurus). That will form a later PR as I think it is somewhat of an edge case in that only @cjhopp and I have really complained so far (#88).

I still think that longer term, working on an Xarray (or similar) interface would be worthwhile.

**Comment by calum-chamberlain** [comment] 2017-07-26 23:15
I'm going to close this one - I think that the new C routines are the fastest of the implementations so far (graph below for short, 172,800 sample arrays, 10 channels and on my i5 with 4-threads). 

![vary_templates](https://user-images.githubusercontent.com/10913395/28647621-5393e674-72bc-11e7-9d9e-aa075c0eef80.png)

You will see that the CV2 (old internals, openCV) run slow in serial, but parallel quite well (which is why they worked well on HPC architectures).  The time domain correlations have not been optimized at all, and I don't know why the parallel loop for that runs slower than the serial... The numpy serial and parallel, and the compiled fftw serial (both python serial and C serial) run at similar speeds, but the parallel fftw loop runs fastest. I think there is more to get out of that too...

I'm going to carry on working on an openMP loop and optimising bits and pieces of the correlation routine alongside the NeSI team, so hopefully it can get faster, but C (or other compiled - fortran might be faster but cba with that) is also the only way I can see to get the memory control we need for large datasets.

**Closed by calum-chamberlain** 2017-07-26 23:15 UTC
Labels: enhancement, ready
