### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ymrou** [eqcorrscan/EQcorrscan#309] opened 2019-06-11 04:02 UTC
Hello, I always have the problem of the list exceeding the index. I think it is wrong to intercept the template earthquake event. How do you intercept the template earthquake event? If it is not the problem, what is the problem? I hope you can help me solve it. .

**Comment by calum-chamberlain** [comment] 2019-06-11 04:05
Please fill out the form when you open the issue and explain what is happening, including an example of your issue.

**Comment by calum-chamberlain** [comment] 2019-06-11 22:57
Closing due to lack of information.

**Comment by ymrou** [comment] 2019-06-12 01:36
Hello, I always have the problem of the list exceeding the index. I think it is wrong to intercept the template earthquake event. How do you intercept the template earthquake event? If it is not the problem, what is the problem? I hope you can help me solve it. 

from eqcorrscan.core.template_gen import from_sac
import glob
import obspy
import eqcorrscan
import os

sac_files = glob.glob(R'./test_data5/*')
print(len(sac_files))
templates = from_sac(sac_files=sac_files, lowcut=1.0, highcut=8.0,
                     samp_rate=100.0, filt_order=4, length=2.0,
                    swin='S', prepick=0.1, all_horiz=True)
print(len(templates))
print(templates)
templates[0].write('template_dt5.ms', format="MSEED")

0
[]
Traceback (most recent call last):
  File "E:/Project/EQ/from_sac.py", line 31, in <module>
    templates[0].write('template_dt5.ms', format="MSEED")
IndexError: list index out of range

**Comment by calum-chamberlain** [comment] 2019-06-12 01:39
You have no SAC files in your list, so no templates are created, so the zeroth element of an empty list results in an error.

You should check that you are pointing to the correct path for your SAC files.

**Comment by ymrou** [comment] 2019-06-12 01:44
> 您的列表中没有SAC文件，因此不会创建任何模板，因此空列表的第0个元素会导致错误。
> 
> 您应该检查是否指向了SAC文件的正确路径。

I have exported the SAC file list, it should not be a problem.
The output program is as follows：

for i in range(len(sac_files)):
     print("*",sac_files[i])
     print(obspy.read(sac_files[i]))
     print(obspy.read(sac_files[i])[0].stats)
     obspy.read(sac_files[i]).plot()


9
* ./test_data5\2018.249.17.46.06.0000.SX.CHS.00.BHE.D.SAC
1 Trace(s) in Stream:
SX.CHS..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: CHS
        location: 
         channel: BHE
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 1277800.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -90.0, 'kinst': 'BBVS-12', 'kcmpnm': 'BHE', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 1277800.0, 'stla': 38.1721, 'depmax': 2737.0, 'lcalda': 0, 'idep': 7, 'depmen': -543.11536, 'npts': 6000, 'delta': 0.01, 'stlo': 112.514, 'cmpaz': 90.0, 'kstnm': 'CHS', 'depmin': -5025.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
* ./test_data5\2018.249.17.46.06.0000.SX.CHS.00.BHN.D.SAC
1 Trace(s) in Stream:
SX.CHS..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: CHS
        location: 
         channel: BHN
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 1268090.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -90.0, 'kinst': 'BBVS-12', 'kcmpnm': 'BHN', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 1268090.0, 'stla': 38.1721, 'depmax': 1890.0, 'lcalda': 0, 'idep': 7, 'depmen': -775.4608, 'npts': 6000, 'delta': 0.01, 'stlo': 112.514, 'cmpaz': 0.0, 'kstnm': 'CHS', 'depmin': -3962.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
* ./test_data5\2018.249.17.46.06.0000.SX.CHS.00.BHZ.D.SAC
1 Trace(s) in Stream:
SX.CHS..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: CHS
        location: 
         channel: BHZ
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 1242610.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -0.0, 'kinst': 'BBVS-12', 'kcmpnm': 'BHZ', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 1242610.0, 'stla': 38.1721, 'depmax': 2826.0, 'lcalda': 0, 'idep': 7, 'depmen': 445.92532, 'npts': 6000, 'delta': 0.01, 'stlo': 112.514, 'cmpaz': -1.0, 'kstnm': 'CHS', 'depmin': -2113.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
* ./test_data5\2018.249.17.46.06.0000.SX.GUJ.00.BHE.D.SAC
1 Trace(s) in Stream:
SX.GUJ..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: GUJ
        location: 
         channel: BHE
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 1263350.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -90.0, 'kinst': 'BBVS-12', 'kcmpnm': 'BHE', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 1263350.0, 'stla': 37.8726, 'depmax': 2784.0, 'lcalda': 0, 'idep': 7, 'depmen': -446.52466, 'npts': 6000, 'delta': 0.01, 'stlo': 111.872, 'cmpaz': 90.0, 'kstnm': 'GUJ', 'depmin': -2931.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
* ./test_data5\2018.249.17.46.06.0000.SX.GUJ.00.BHN.D.SAC
1 Trace(s) in Stream:
SX.GUJ..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: GUJ
        location: 
         channel: BHN
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 1261780.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -90.0, 'kinst': 'BBVS-12', 'kcmpnm': 'BHN', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 1261780.0, 'stla': 37.8726, 'depmax': 5774.0, 'lcalda': 0, 'idep': 7, 'depmen': -1890.4376, 'npts': 6000, 'delta': 0.01, 'stlo': 111.872, 'cmpaz': 0.0, 'kstnm': 'GUJ', 'depmin': -6389.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
* ./test_data5\2018.249.17.46.06.0000.SX.GUJ.00.BHZ.D.SAC
1 Trace(s) in Stream:
SX.GUJ..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: GUJ
        location: 
         channel: BHZ
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 1242890.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -0.0, 'kinst': 'BBVS-12', 'kcmpnm': 'BHZ', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 1242890.0, 'stla': 37.8726, 'depmax': 4695.0, 'lcalda': 0, 'idep': 7, 'depmen': 2390.3787, 'npts': 6000, 'delta': 0.01, 'stlo': 111.872, 'cmpaz': -1.0, 'kstnm': 'GUJ', 'depmin': -820.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
* ./test_data5\2018.249.17.46.06.0000.SX.LOF.00.BHE.D.SAC
1 Trace(s) in Stream:
SX.LOF..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: LOF
        location: 
         channel: BHE
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 610080.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -90.0, 'kinst': 'CMG-3ES', 'kcmpnm': 'BHE', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 610080.0, 'stla': 38.0411, 'depmax': -5994.0, 'lcalda': 0, 'idep': 7, 'depmen': -8551.812, 'npts': 6000, 'delta': 0.01, 'stlo': 111.9509, 'cmpaz': 90.0, 'kstnm': 'LOF', 'depmin': -11601.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
* ./test_data5\2018.249.17.46.06.0000.SX.LOF.00.BHN.D.SAC
1 Trace(s) in Stream:
SX.LOF..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: LOF
        location: 
         channel: BHN
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 609460.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -90.0, 'kinst': 'CMG-3ES', 'kcmpnm': 'BHN', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 609460.0, 'stla': 38.0411, 'depmax': -6222.0, 'lcalda': 0, 'idep': 7, 'depmen': -8489.683, 'npts': 6000, 'delta': 0.01, 'stlo': 111.9509, 'cmpaz': 0.0, 'kstnm': 'LOF', 'depmin': -13005.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
* ./test_data5\2018.249.17.46.06.0000.SX.LOF.00.BHZ.D.SAC
1 Trace(s) in Stream:
SX.LOF..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
         network: SX
         station: LOF
        location: 
         channel: BHZ
       starttime: 2018-09-06T17:46:06.000000Z
         endtime: 2018-09-06T17:47:05.990000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 6000
           calib: 606360.0
         _format: SAC
             sac: AttribDict({'e': 60.0, 'kevnm': '', 'stel': 0.0, 'leven': 1, 'lpspol': 0, 'nzmin': 46, 'cmpinc': -0.0, 'kinst': 'CMG-3ES', 'kcmpnm': 'BHZ', 'nzyear': 2018, 'b': 0.0, 'iztype': 9, 'nzsec': 6, 'scale': 606360.0, 'stla': 38.0411, 'depmax': -7701.0, 'lcalda': 0, 'idep': 7, 'depmen': -9074.021, 'npts': 6000, 'delta': 0.01, 'stlo': 111.9509, 'cmpaz': -1.0, 'kstnm': 'LOF', 'depmin': -11230.0, 'nzjday': 249, 'iftype': 1, 'nzhour': 17, 'knetwk': 'SX', 'nzmsec': 0, 'nvhdr': 6})
D:\anaconda3\envs\EQ\lib\site-packages\obspy\signal\detrend.py:31: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(data.dtype, float):
0
[]
Traceback (most recent call last):
  File "E:/Project/EQ/from_sac.py", line 31, in <module>
    templates[0].write('template_dt5.ms', format="MSEED")
IndexError: list index out of range

**Comment by ymrou** [comment] 2019-06-12 01:47
I can use the SAC data you provided to generate a template, but I can't generate a template with my own data. Do you have some data pre-processing? If so, what do you do?

**Comment by calum-chamberlain** [comment] 2019-06-12 01:50
It looks like you didn't copy the output length of `sac_files` in the previous comment, I assumed the `0` was the output from `print(len(sac_files))`, but I guess not. See issue #300, the questions asked there still stand:

Can you confirm that:

- [x] sac_files is a list of sac files (you have confirmed this);
- [ ] Your sac files have picks associated with them;
- [ ] The picks are stored in the headers expected by from_sac (from the docs for sactoevent:
> Picks are taken from header values a, t[0-9]

**Comment by ymrou** [comment] 2019-06-12 01:53
I don't know the sentence " Your sac files have picks associated with them;", can you explain it?

**Comment by calum-chamberlain** [comment] 2019-06-12 01:57
Have you made phase-picks for your data and are they stored in the SAC headers in the correct place (see point 3)?

The templates made by the `template_gen` functions are simply processed, trimmed waveforms cut around phase picks. Phase picks in SAC are stored in the SAC headers. The `template_gen` routines need to know when to cut around.  If there are no picks then no template will be created.

**Comment by ymrou** [comment] 2019-06-12 02:00
I don't seem to have gone through the third operation. Is there any specific requirement for the operation of "trimmed waveforms cut around phase picks"?

**Comment by calum-chamberlain** [comment] 2019-06-12 02:02
You do not do the trimming, the `template_gen` functions (in your case `from_sac`) do the trimming based on the picks you make. 

From your output above it doesn't look like you have picks in the SAC files. Make picks and put them in the SAC headers, or put picks that were made previously into the headers and rerun.

**Comment by ymrou** [comment] 2019-06-18 01:15
Hello, I saved the initial phase of the earthquake to t0 and re-run it. I still have the above problem. I want to ask what is the reason?

**Comment by calum-chamberlain** [comment] 2019-06-18 01:21
Do you just get the same empty template?

If so, can you try running something along the lines of:
```python
from obspy import read, Stream
from eqcorrscan.utils.sac_util import sactoevent

st = Stream()
for sac_file in sac_files:
    # sac_files should be as above - the list of sac-files to be read in for the template
    st += read(sac_file)
print(st)
event = sactoevent(st)
print(event)
for pick in event.picks:
    print(pick)
```
This should confirm that picks are being read in by `sactoevent` (used internally in the template generation functions for construct an event as required for template generation).

Can you paste the output from this here please.

**Comment by ymrou** [comment] 2019-06-18 01:36
The output is as follows:
SX.CHS..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
  File "E:/Project/EQ/test_1.py", line 12, in <module>
SX.CHS..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.CHS..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
    print(event)
SX.GUJ..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.GUJ..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
  File "D:\anaconda3\envs\EQ\lib\site-packages\obspy\core\event\event.py", line 133, in __str__
SX.GUJ..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
    self.short_str(),
SX.LIS..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
  File "D:\anaconda3\envs\EQ\lib\site-packages\obspy\core\event\event.py", line 119, in short_str
SX.LIS..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
    origin.longitude)
SX.LIS..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
TypeError: a float is required
SX.LOF..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.LOF..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.LOF..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples

**Comment by calum-chamberlain** [comment] 2019-06-18 01:39
Looks like something went wrong there. The output order is all wrong.  Can you just paste the output from:
```python
for pick in event.picks:
    print(pick)
```

**Comment by ymrou** [comment] 2019-06-18 01:42
12 Trace(s) in Stream:
Traceback (most recent call last):
  File "E:/Project/EQ/test_1.py", line 12, in <module>
SX.CHS..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
    print(event)
SX.CHS..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
  File "D:\anaconda3\envs\EQ\lib\site-packages\obspy\core\event\event.py", line 133, in __str__
SX.CHS..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.GUJ..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.GUJ..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.GUJ..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.LIS..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.LIS..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.LIS..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.LOF..BHE | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.LOF..BHN | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
SX.LOF..BHZ | 2018-09-06T17:46:06.000000Z - 2018-09-06T17:47:05.990000Z | 100.0 Hz, 6000 samples
    self.short_str(),
  File "D:\anaconda3\envs\EQ\lib\site-packages\obspy\core\event\event.py", line 119, in short_str
    origin.longitude)
TypeError: a float is required

Process finished with exit code 1

**Comment by calum-chamberlain** [comment] 2019-06-18 01:46
> Can you just paste the output from:
> 
> for pick in event.picks:
>     print(pick)

**Comment by calum-chamberlain** [comment] 2019-06-18 01:57
So the event does not have an origin, so `print(event)` will not work. Can you please copy the output from:
```python
for pick in event.picks:
    print(pick)
```

**Comment by ymrou** [comment] 2019-06-18 01:59
I just replied to you all the output, the following is my code:
import glob
from obspy import read, Stream
from eqcorrscan.utils.sac_util import sactoevent

sac_files = glob.glob(R'./test_data5/*')
st = Stream()
for sac_file in sac_files:
    # sac_files should be as above - the list of sac-files to be read in for the template
    st += read(sac_file)
print(st)
event = sactoevent(st)
print(event)

for pick in event.picks:
    print(pick)

**Comment by calum-chamberlain** [comment] 2019-06-18 02:13
The code has not worked due to the error relating to no origin:
```python
TypeError: a float is required
```
So the section following that that prints the picks did not run. Please paste the output from:
```python
for pick in event.picks:
    print(pick)
```

**Comment by calum-chamberlain** [comment] 2019-06-18 22:33
So just to clarify: your SAC files do not contain any origin information (the timing and location of a seismic source), but this is **not** needed to make a template, so this is not an issue. However, obspy will fail to print an event without any origin information, hence the error.  Because we don't care about this, printing out just the pick information (as requested above) would help to debug why you are still not getting a template when you think the picks have been stored in the correct place.

*However:* because you are using the old API (functions rather than objects) all a template is in this case is a processed, cut waveform.  If you are happy with your SAC file (you have processed and cut it how you want) then there is no need to use the `template_gen` functions at all: you can just use your `Stream` as a template for the `matched_filter` functions.

A note: it looks like you are using Windows, and it also looks like you are writing scripts for everything.  For debugging this kind of thing the iPython shell is really handy - one of the great things about Python being an interpreted language is that you can query what is in memory and what your variables are on the fly, without having to write scripts and debug them.  If you are not using this already I **strongly** recommend installing this and using it.

A final note: Python error messages tend to be helpful. It is worth taking the time to read them and understand them. They usually point to the line of code that caused the issue and give relatively explicit reasons for raising an error.

**Comment by ymrou** [comment] 2019-06-19 03:10
For yesterday's question, the output is as follows:
Event:   2018-08-31T18:27:36.000000Z  |  None, None

              resoure_id: ResourceIdentifier(id="si:local/85dc299e-438-4a64-99fc-6a918bc1c0")
                       -----------
                  origins: 1 Elements

**Comment by calum-chamberlain** [comment] 2019-06-19 03:26
I'm not sure what you have printed there? Is that the `event`? If so it looks like no picks have been read in (if picks were read in, beneath `origins` there would be a `picks` section).

You can run `sactoevent(st=st, debug=3)` to get the function to output more useful information.  Can you also check that you are running a recent version of obspy (>= 1.0.0), and confirm that your picks are read in to the `sac_header` dictionary in `Trace.stats`: e.g. you said you saved picks into t0, so I would expect the output from the following to be your pick-times:

```python
from obspy import read, Stream

st = Stream() 
for sac_file in sac_files:
    # sac_files is as before
    st += read(sac_file)
for tr in st:
    print(tr.stats.sac['t0'])
```

**Comment by ymrou** [comment] 2019-06-19 03:40
The output is as follows:
139.89142
139.89142
139.89142
139.89142
139.89142
139.89142
139.89142
139.89142
139.89142

**Comment by calum-chamberlain** [comment] 2019-06-19 03:46
Great, so they are read in by obspy, now to figure out why they don't get through sactoevent.  This would probably be simplest if you sent me the SAC files, or you can continue to try and work it out.

**Comment by calum-chamberlain** [comment] 2019-06-19 03:49
My guess is that the pick-hint in kt0 isn't populated?

**Comment by ymrou** [comment] 2019-06-20 01:31
Hello, here are some of the data I provided (data sent in new form of attachment), please help me




------------------ 原始邮件 ------------------
发件人: "Calum Chamberlain"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 中午11:49
收件人: "eqcorrscan/EQcorrscan"<EQcorrscan@noreply.github.com>;
抄送: "矛木"<378635821@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eqcorrscan/EQcorrscan] IndexError: list index out of range(#309)




My guess is that the pick-hint in kt0 isn't populated?

**Comment by calum-chamberlain** [comment] 2019-06-20 01:33
Email attachments are not passed - you can add files by drag-and-dropping them on github, or email me directly.

**Comment by ymrou** [comment] 2019-06-20 01:36
[test_data.zip](https://github.com/eqcorrscan/EQcorrscan/files/3308425/test_data.zip)

**Comment by calum-chamberlain** [comment] 2019-06-20 01:44
Those data have no picks in the t0 (or any other t[0-9] slot). These will not work. I assume this isn't the data you were using yesterday that had picks in t0?

**Comment by ymrou** [comment] 2019-06-20 01:50
Sorry, I sent you a wrong data, and now I am sending the correct data.
[test_data.zip](https://github.com/eqcorrscan/EQcorrscan/files/3308446/test_data.zip)

**Comment by calum-chamberlain** [comment] 2019-06-20 02:15
Okay, so `sactoevent` also needs to know what type of pick it is - you do that by specifying the phase type in kt[0-9] (in your case in kt0).  This is not clear in the docs. What I did to make this work is:
```python
import glob
from eqcorrscan.core.template_gen import template_gen
from obspy import read

sac_files = glob.glob("*.SAC")
for sac_file in sac_files:
    tr = read(sac_file)[0]
    tr.stats.sac.update({'kt0': 'S'})
    tr.write(sac_file)

templates = template_gen(
    method="from_sac", sac_files=sac_files, lowcut=1.0, highcut=8.0, 
    samp_rate=100.0, filt_order=4, length=2.0, 
    swin='all', prepick=0.1)

print(templates[0])
"""
9 Trace(s) in Stream:
SX.GUJ.00.BHE | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
SX.GUJ.00.BHN | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
SX.GUJ.00.BHZ | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
SX.LIS.00.BHE | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
SX.LIS.00.BHN | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
SX.LIS.00.BHZ | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
SX.LOF.00.BHE | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
SX.LOF.00.BHN | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
SX.LOF.00.BHZ | 2018-09-01T16:48:01.800000Z - 2018-09-01T16:48:03.790000Z | 100.0 Hz, 200 samples
"""
```

Some notes:
1. It is strange to use the same offset for all traces - the picks would usually correspond to phase arrivals.  In this case they do not. Maybe that is just for testing, but to get a good result you should make sure that your picks correspond to the event you want to use as a template;
2. Because you have put a pick in all traces you do not need to select `all_horiz=True`. If you do you will get duplicated channels because each pick will be used to cut around all of the channels
3. If you set `kt0` to be 'P' and `swin='S'` you will get an empty template (and vice-versa). You likely want to use all phases, so just set `swin='all'` as above.
4. You probably want to play with your filters. It looks like you have a nice high-frequency earthquake, so cutting energy above 8Hz might not give you the best result.
5. The function `from_sac` is being depreciated and will not be included in the next release (as you should have have been warned about when you used it, providing you are using the most recent version) - use the `template_gen(method='from_sac', ...)` function instead.
6. If you have picks in **any** format readable by obspy `read_events` you will probably find your life to be considerably simpler using the `template_gen(method='from_meta_file', meta_file='some_pick_file', st=some_stream, ...)` function.  The meta_file can be any file readable by obspy, or an obspy `Catalog` in memory. You can then pass your `Stream` created by reading in your sac files.

**Comment by calum-chamberlain** [comment] 2019-07-30 22:26
Closing due to lack of activity.

**Closed by calum-chamberlain** 2019-07-30 22:26 UTC
Labels: question

**Comment by ymrou** [comment] 2019-08-25 10:22
Hello, I want to ask you questions about converting from template to Template and Tripe objects.

**Comment by calum-chamberlain** [comment] 2019-08-25 22:08
In general, if you have a new issue you should open a new issue.  Before you do though, have you read [this section](https://eqcorrscan.readthedocs.io/en/latest/tutorials/template-creation.html#converting-from-templates-to-template-and-tribe-objects) of the docs?
