### ISSUE TITLE
Can't test EQCorrscan after cloning the git repository

### ISSUE THREAD

**Issue by peace001** [eqcorrscan/EQcorrscan#303] opened 2019-05-12 18:46 UTC
**Describe the bug**
I have cloned the git repository and run python setup.py install, which worked ok.
Now, I am trying to run the tests as instructed, through running python setup.py test.  
This is the error I get: 
collecting 346 items / 2 errors / 344 selected  

**_INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_namespace' in plugin <module 'conftest' from '/home/rockefeller/EQcorrscan/conftest.py'>_**

I have tried to upgrade the pluggy module to 0.11.0  and trying updating and downgrading (back and forth) pytest from  3.7 to  4.0.2.  Still, it does not work.
I am running a Linux 64bit Ubuntu 17.10

What could I do?

**Comment by calum-chamberlain** [comment] 2019-05-12 19:45
I'm struggling to reproduce this with either pytest 3.7.0 or 3.10.0 with Python 3.7.3 and pluggy 0.11.0.  pytest did remove the `pytest_namespace` hook for pytest 4.x in [this pr](https://github.com/pytest-dev/pytest/pull/4421).  Updating the tests to not use this feature is on my long to-do list, but we should be able to get this to work with an older version of pytest.

I have a couple of questions to try and help us work out what is going on:
1. Do you get the same error regardless of pytest version?
2. What version of Python are you using?
3. Are you running this in a conda environment, and if so, can you [share the environment.yml](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#id12) file so that I can try and reproduce your environment?

**Comment by peace001** [comment] 2019-05-13 15:29
Thanks for the assistance
1. I have tried pytest 3.7.0 , 4.0.2 , still the same error
The curious thing is even when I conda install pytest 3.7.0 for instance, right before the test strarts I could read this message  
================================================================ test session starts ================================================================
**platform linux -- Python 3.6.8, pytest-4.4.2, py-1.5.2, pluggy-0.11.0
rootdir: /home/rockefeller/EQcorrscan, inifile: pytest.ini
plugins: forked-1.0.2, xdist-1.28.0, rerunfailures-7.0, pep8-1.0.6, cov-2.7.1
collecting 340 items / 2 errors / 338 selected**   
But I am not running pytest 4.4.2

2.  I am using python 3.6.8 under anaconda 
3. Here is the file 
[environment.txt](https://github.com/eqcorrscan/EQcorrscan/files/3173639/environmentYML.txt)

**Comment by calum-chamberlain** [comment] 2019-05-13 19:04
It looks like you are running pytest 4 still. Please make sure you install pytest 4 and try again.

CJ Chamberlain, out of office

________________________________

**Comment by calum-chamberlain** [comment] 2019-05-16 01:29
PR #305 should have fixed the issues with testing with pytest 4.x, but it's going to a while before I get things up to master and put out a new release. Let me know if uninstalling pytest 4.x and installing 3.x didn't work, otherwise I'm going to close this.

**Closed by calum-chamberlain** 2019-05-16 01:29 UTC
Labels: tests
