### ISSUE TITLE
[DOCS] lag_calc errors in Quick-Start tutorial.

### ISSUE THREAD

**Issue by dr-glenn** [eqcorrscan/EQcorrscan#429] opened 2020-09-20 00:42 UTC
I wanted to run the Parkfield example in [section 4.1.1](https://eqcorrscan.readthedocs.io/en/latest/tutorials/quick_start.html) of the Quick Start Tutorial. I ran in jupyter and got results that appeared identical until the lag_calc step. At that point I got hundreds of errors, such as:

> 2020-09-16 09:29:29,237	eqcorrscan.core.lag_calc	ERROR	lag-calc has decreased cccsum from 15.190760 to 1.000000 - 
2020-09-16 09:29:29,244	eqcorrscan.core.lag_calc	ERROR	lag-calc has decreased cccsum from 2.694359 to 0.190477 - 
2020-09-16 09:29:29,250	eqcorrscan.core.lag_calc	ERROR	lag-calc has decreased cccsum from 4.138291 to 0.178131 - 
2020-09-16 09:29:29,258	eqcorrscan.core.lag_calc	ERROR	lag-calc has decreased cccsum from 3.870528 to 0.214845 - 

I then exported the notebook as pure Python and tried to run. This has more problems, but I'll file a separate issue for that.

**To Reproduce**
I created a Jupyter notebook and simply copy/pasted the code from the above referenced web page.

**Expected behavior**
I didn't expect to see so many lag_calc errors, and looking at the source code did not help me understand what went wrong - if anything.
Up to the lag_calc everything appeared to be the same as in the published example. The traces appeared identical.

**Desktop (please complete the following information):**
 - Operating System: Windows 10 Pro
 - Anaconda, Python version: 3.7.8
 - EQcorrscan version: Don't know. I used "conda install" a week ago.
- ObsPy version: also conda install a week ago.

**Comment by calum-chamberlain** [comment] 2020-09-20 06:49
Hi Glenn, thanks for reporting this. Two quick points:
1. You are right, you shouldn't be getting errors like this, sorry;
2. I can reproduce this.

It might take me a while to find and fix the underlying issue here. I have some suspicions. but I also have a very busy next three weeks. Please ping me if I haven't responded more helpfully in a week!

**Comment by calum-chamberlain** [comment] 2020-09-20 22:31
I actually found the issue here - this is due to how overlaps in the downloaded stream have been handled. To fix this, the line:
```python
st = st.merge()
```
just before running lag-calc should be changed to:
```python
st = st.merge(method=1)
```

This change is related to the changes to [allow poor quality data](https://github.com/eqcorrscan/EQcorrscan/commit/1925c6900a26263b85d5d1a890b740d7db4a37b3), of variable lengths. Unfortunately this change seems to have broken the tutorial. Thanks for letting me know. I will update the tutorial now.

**Comment by calum-chamberlain** [comment] 2020-10-09 20:39
Closing this issue after the fix to the tutorial in [this commit](https://github.com/eqcorrscan/EQcorrscan/commit/2dc3940a2cb20562148fdd08bda07c4c93fd9ec6).

Thanks again for letting us know about this - I really appreciate it!

**Closed by calum-chamberlain** 2020-10-09 20:39 UTC
Labels: core.lag_calc, docs
